export   const GET_SETTINGS_DATA = 'APP/GET_SETTINGS_DATA';
export   const SET_SETTINGS_DATA = 'APP/SET_SETTINGS_DATA';
export   const SET_MENU = 'APP/SET_MENU';
export   const GET_MENUS = 'APP/GET_MENUS';
export   const GET_INITIAL_DATA = 'APP/GET_INITIAL_DATA';